// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace XieSender
{
    internal static unsafe partial class Kernel32
    {
        const string __DllName = "kernel32";





        [DllImport(__DllName, EntryPoint = "GetCurrentThread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* GetCurrentThread();

        [DllImport(__DllName, EntryPoint = "SetThreadAffinityMask", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint SetThreadAffinityMask(void* hThread, nuint dwThreadAffinityMask);


    }



}
