// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace XieSender
{
    internal static unsafe partial class XInput
    {
        const string __DllName = "XInput1_4";





        [DllImport(__DllName, EntryPoint = "XInputGetState", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint XInputGetState(uint dwUserIndex, XINPUT_STATE* pState);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct XINPUT_GAMEPAD
    {
        public ushort wButtons;
        public byte bLeftTrigger;
        public byte bRightTrigger;
        public short sThumbLX;
        public short sThumbLY;
        public short sThumbRX;
        public short sThumbRY;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct XINPUT_STATE
    {
        public uint dwPacketNumber;
        public XINPUT_GAMEPAD Gamepad;
    }



}
