name: dotnet-test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Generate C# bindings from Rust
        run: cargo build --release
        working-directory: ./src/xie_sender_generator
      - name: Format generated code
        run: dotnet format
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
      - name: Find coverage output path
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path . -Filter "coverage.cobertura.xml" -Recurse -File
          foreach ($file in $files) {
              Copy-Item -Path $file.FullName -Destination . -Force
          }
      - name: Run ReportGenerator
        shell: pwsh
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"coverage.cobertura.xml" -targetdir:"report" -reporttypes:"Html;MarkdownSummary"
          Get-Content report/Summary.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8
      - uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: report/